description: open-agentrl-qwen3-4b-sft

target:
  service: sing
  workspace_name: srgxws
  name: palisades33

environment:
  image: amlt-sing/acpt-torch2.7.1-py3.10-cuda12.6-ubuntu22.04
  setup:
  - sudo apt update

code:
  local_dir: $CONFIG_DIR
  ignore:
    - .git
    - /checkpoints/
    - /checkpoint/
    - wandb/
    - verl.egg-info/
    - __pycache__/
    - .venv/
    - amlt/
    - /outputs/
    - figs/
    - /output/
    - flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl

data:
    local_dir: /home/v-tianshixu/pretrained_model/Qwen3-4B-RA-SFT
    remote_dir: pretrained_model/

jobs:
- name: open-agentrl-qwen3-4b-sft
  sku: 1x40G8-A100
  identity: managed
  priority: high
  submit_args:
    env:
      NCCL_DEBUG: "ERROR"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e546c811-2312-46e2-9fd0-c949c65da4d9/resourcegroups/srgx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/srgxuai
  command:
  - nvidia-smi
  - cat /etc/issue
  - curl -LsSf https://astral.sh/uv/install.sh | sh
  - source $$HOME/.local/bin/env
  - uv python install 3.11
  - uv venv -p 3.11
  - source .venv/bin/activate
  - which python
  - python --version
  - uv pip sync requirements.txt
  - uv pip install --no-cache-dir flash_attn-2.7.4.post1+cu12torch2.6cxx11abiFALSE-cp311-cp311-linux_x86_64.whl
  - uv pip install -e .[vllm]
  - uv pip list
  - bash recipe/demystify/qwen3_4b_sft_custom.sh