description: open-agentrl-qwen3-4b-rl

target:
  service: sing
  workspace_name: srgxws
  name: msrresrchbasicvc

environment:
  image: verl_origin:v1
  registry: srgxacr.azurecr.io

data:
    local_dir: /home/v-tianshixu/pretrained_model/Qwen3-4B-RA-SFT
    remote_dir: pretrained_model/

code:
  local_dir: $CONFIG_DIR
  ignore:
    - .git
    - /checkpoints/
    - /checkpoint/
    - /wandb/
    - __pycache__/
    - .venv/
    - /amlt/
    - /outputs/
    - /figs/
    - /output/
    - /pretrained_model/
    - code-judge/server.log
    - code-judge/worker.log
    - /SandboxFusion/

jobs:
- name: sglang-v3-context-edit
  sku: 1x80G8
  identity: managed
  priority: high
  submit_args:
    env:
      NCCL_DEBUG: "ERROR"
      _AZUREML_SINGULARITY_JOB_UAI: /subscriptions/e546c811-2312-46e2-9fd0-c949c65da4d9/resourcegroups/srgx/providers/Microsoft.ManagedIdentity/userAssignedIdentities/srgxuai
      VERL_LOGGING_LEVEL: "INFO"
      VERL_TOOL_PARSER_ENABLE_REPAIR: "1"
      VERL_TOOL_PARSER_ENABLE_FEEDBACK: "0"
  command:
    - ls
    - export DEBIAN_FRONTEND=noninteractive
    - export PATH="/home/aiscuser/.local/bin:$$PATH"
    - sudo apt-get update -y
    - sudo apt install tmux -y
    - sudo apt-get install -y libglib2.0-0
    - cat sing_rl_sglang.yml
    - pip install -r code-judge/requirements.txt
    - pip install -e code-judge
    - sudo apt-get install redis -y
    - redis-server --daemonize yes --protected-mode no --bind 0.0.0.0
    - redis-cli ping
    - tmux new-session -d -s server 'cd ./code-judge &&  MAX_EXECUTION_TIME=4 REDIS_URI="redis://localhost:6379" RUN_WORKERS=0 uvicorn app.main:app --host 0.0.0.0 --port 8088 --workers 16 2>&1 | tee server.log'
    - tmux new-session -d -s worker 'cd ./code-judge &&  MAX_EXECUTION_TIME=4  REDIS_URI="redis://localhost:6379" MAX_WORKERS=64  python run_workers.py 2>&1 | tee worker.log'
    - pip install json-repair math_verify
    - which python
    - cd verl && pip3 install -e .[sglang] && cd ..
    - cat recipe/demystify/grpo_tcr_qwen3_4b.sh
    - bash recipe/demystify/grpo_tcr_qwen3_4b.sh